### ISSUE TITLE
Custom `Drop` detaches all descendants, even if they are shared

### ISSUE THREAD

**Issue by lo48576** [RazrFalcon/rctree#11]
```rust
#[test]
fn keep_subtree() {
    fn create_tree() -> Node<&'static str> {
        let mut n1 = Node::new("1");
        let n1_1 = Node::new("1-1");
        n1.append(n1_1);
        let mut n1_2 = Node::new("1-2");
        n1.append(n1_2.clone());
        let n1_2_1 = Node::new("1-2-1");
        n1_2.append(n1_2_1);
        let n1_3 = Node::new("1-3");
        n1.append(n1_3);
        // 1
        // |-- 1-1
        // |-- 1-2
        // |   `-- 1-2-1
        // `-- 1-3

        // And, return subtree 1-2.
        n1_2
    }

    let n1_2 = create_tree();
    // `n1_2` should have a child `n1_2_1`.
    assert!(n1_2.first_child().is_some());
}
```

This test passes without custom `impl Drop`, but fails with current implementation.

This is because the current custom `Drop` detaches all descendants without checking if they are shared.
In contrast, without custom `Drop`, `NodeData` will be modified (destroyed) only if `Rc`'s strong refcount is 1.

Is this behavior intended?
I've expected default (implicit) drop behavior and I'm surprised when noticed this difference.

**Comment by RazrFalcon** [comment]
Yes, you cannot share nodes between "trees". This should be noted somewhere since we cannot enforce it, afaik.

**Comment by tajtiattila** [comment]
This does not just prohibit sharing nodes between trees but also holding on to subtrees.

In my case, I use usvg (that uses rctree internally) and have an SVG with a different graphic in each layer.

I want to keep references to the layers themselves only, but that doesn't work because the custom `Drop` removes the children of subtrees when the root SVG is dropped.

I find this really unintuitive while looking for a problem with `Node`s disappearing. I checked rctree first but I saw it uses `Rc` internally so it can't be the problem. It didn't occur to me that there is a custom `Drop` implementation that somewhat defeats the purpose of using `Rc` in the first place.

**Comment by RazrFalcon** [comment]
This issue is a bit out of date. There are no more root node link.

As for Drop, I honestly do not remember why it was added in the first place. It was a long time ago.
Probably this: https://github.com/RazrFalcon/rctree/commit/95128aca8a8b1914cc0c7d3a532a95ebbb426d3e

I'm not sure if it still needed.

**Comment by RazrFalcon** [comment]
Yes, we do

```
thread 'stack_overflow' has overflowed its stack
fatal runtime error: stack overflow
```

So Drop is required, because deeply nested Rc would cause a stack overflow.

If you have a better solution - please send a patch.
